### PR TITLE
bump client lib version, fix bug with passing version

### PR DESCRIPTION
**Pull request by tanjabrzak**
# Jira

[DATAENG-747](https://lumoslabs.atlassian.net/browse/DATAENG-747)

# Description

We got a notification from Google telling us to update the Google Ads API version since our current version (13) got deprecated and will stop accepting requests on 31st January:

Dear Google Ads API developer (manager account ID 326-511-1329),

Google Ads API v13 has been deprecated and will stop accepting requests starting on January 31, 2024.

Your developer token has recently submitted requests to v13. Migrate to the latest version as soon as possible to continue accessing the Google Ads API. Use the migration guide to upgrade.

If you have any questions, please don't hesitate to contact us at [googleadsapi-support@google.com](mailto:googleadsapi-support@google.com).

This needs to be addressed quickly!

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation change only

# How Has This Been Tested?
running report downloader from local 

# Related PRs

https://github.com/lumoslabs/infrastructure-core-setup/pull/669

# Checklist:

- [ ] My code follows the [data engineering style guidelines](https://github.com/lumoslabs/engineering_guide/tree/master/data_engineering#style-guidelines)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# To Do:
Merge and depoy related PR

[DATAENG-747]: https://lumoslabs.atlassian.net/browse/DATAENG-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by joycelau1** [comment]
@tanjabrzak code looks ok but can u verify how it was tested by completing the description template please.  I've added the template here and also created the same default template as other data repos.

**Review by PalSzabolcs — APPROVED** [review]
👍 
but please address the comments from @joycelau1 before merging

**Comment by gtskaushik** [comment]
Merging this PR on behalf of @tanjabrzak due to an issue with access

**Comment by joycelau1** [comment]
@tanjabrzak in future PR, please go thru the checklist in the description template and check all items applied.

**Pull request merged**
